# Generated by Django 3.1.13 on 2021-12-11 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(help_text='Senior one', max_length=30)),
                ('class_short_form', models.CharField(help_text='S1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('admission_date', models.DateField()),
                ('name', models.CharField(help_text='John Doe', max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20)),
                ('section', models.CharField(max_length=100)),
                ('shift_name', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(help_text='John Doe', max_length=100)),
                ('emergency_phone', models.IntegerField(null=True, unique=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=30, null=True)),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentclassinfo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='create', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], default='Present', max_length=15)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentinfo')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
